language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t kowal001/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true kowal001/react-test npm run test

after_succes:
    - docker build -t kowal001/multi-client ./client
    - docker build -t kowal001/multi-nginx ./nginx
    - docker build -t kowal001/multi-server ./server
    - docker build -t kowal001/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push kowal001/multi-client
    - docker push kowal001/multi-nginx
    - docker push kowal001/multi-worker
    - docker push kowal001/multi-server

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-956482773113"
    bucket_path: "docker-multi"
    on:
     branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY